### PR TITLE
Task/acc 119 unique tax name

### PR DESCRIPTION
**Pull request by stevespur**
Update city/county tax names to include state

### CODE REVIEW

**Comment by maybenull** [comment]
does this get all the county taxes too?

**Comment by stevespur** [comment]
Should get all alabama occupational and maryland counties. Those were the only ones I saw that were not state specific

**Comment by rmcdaniel** [comment]
This is kind of a scary migration. Let's test this on accounting clone first?

**Comment by stevespur** [comment]
should happen when tasie tests, yea?

**Pull request merged**
